argo-workflows:
  controller:
    workflowDefaults:
      spec:
        ttlStrategy:
          secondsAfterCompletion: 84600 # 1 day
    persistence:
      archive: true
      postgresql:
        host: postgres.postgres.svc.cluster.local
        port: 5432
        database: workflow
        tableName: argo_workflows
        userNameSecret:
          name: argo-postgres-config
          key: username
        passwordSecret:
          name: argo-postgres-config
          key: password
        ssl: false
        sslmode: disable
  useDefaultArtifactRepo: true
  artifactRepository:
    archiveLogs: true
    s3:
      bucket: workflows
      endpoint: minio.minio.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: minio-creds
        key: accesskey
      secretKeySecret:
        name: minio-creds
        key: secretkey
